### ISSUE TITLE
Compilation and binaries

### ISSUE THREAD

**Issue by TanahLot** [eglaysher/rldev#1]
I'm try compile it and can't nor Linux or Windows. I'm try search root of problem. And I'm [find instruction](https://www.baka-tsuki.org/project/index.php?title=OCamlInstall) with "Note: Newer versions of OCaml and Ulex won't work". But even oldstable Debian repository don't have so old versions of OCaml and Ulex. Okay, I'm try use Cygwin and doing what this instruction say. And I'm can't find some request packages in Cygwin. For example - libpng14-devel. I'm try use similar packages... And I'm can't compile even old version of OCAML. For more complicate, instruction request 32-bit Windows XP. But cygwin already drop support of XP ([NOTE: The previous Cygwin version 2.5.2 was the last version supporting Windows XP and Server 2003.](http://cygwin.com/)).

Maybe I'm doing this wrong. Maybe this is problem in old code. In any case, can you add release with already compiled binaries?

**Comment by eglaysher** [comment]
IIRC, you need to an entire build environment from about 2006, including old copies of ocmal, omake, along with all libraries that rldev depended on. Everything from the build system up needs to be from this era. (I vaguely remember reading that there were breaking language changes in the ocaml parser which are one of the reasons that this code just won't compile.)

This repository should mostly be treated as a historical archive. I haven't successfully built this in half a decade. There's a reason that I gave up in rlvm and checked in the compiled binaries for the test cases instead of continuing to rely on rldev.
